const sexoIds = {
  ["Feminino"]: "2",
  ["Masculino"]: "1",
};

const nacionalidadIds = {
  ["Brasil"]: "26",
  ["Federação da Rússia"]: "61",
  ["Turquia"]: "182",
  ["Ucrânia"]: "184",
};

const estadoCivilIds = {
  ["Casado"]: "140",
  ["Divorciado"]: "143",
  ["Soltero"]: "139",
  ["União livre"]: "141",
  ["Viúvo"]: "142",
};

const paisNacimientoIds = {
  ["Afeganistão"]: "1",
  ["Albânia"]: "2",
  ["Alemanha"]: "3",
  ["Andorra"]: "4",
  ["Angola"]: "5",
  ["Anguilla"]: "225",
  ["Antígua e Barbuda"]: "6",
  ["Antilhas Neerlandesas (Antilhas Holandesas)"]: "223",
  ["Arábia Saudita"]: "7",
  ["Argélia"]: "8",
  ["Argentina"]: "9",
  ["Armênia"]: "10",
  ["Aruba"]: "222",
  ["Austrália"]: "11",
  ["Áustria"]: "12",
  ["Azerbaijão"]: "13",
  ["Bahamas"]: "14",
  ["Bareine (Bahrein)"]: "15",
  ["Bangladeche (Bangladesh)"]: "16",
  ["Barbados"]: "17",
  ["Bielorrússia (Belarus)"]: "18",
  ["Bélgica"]: "19",
  ["Belize"]: "20",
  ["Benin"]: "21",
  ["Bermudas"]: "226",
  ["Butão"]: "22",
  ["Bósnia e Herzegovina"]: "24",
  ["Botsuana"]: "25",
  ["Brasil"]: "26",
  ["Brunei Darussalam"]: "27",
  ["Bulgária"]: "28",
  ["Burkina Faso"]: "29",
  ["Burundi"]: "30",
  ["Cabo Verde"]: "31",
  ["Camboja"]: "32",
  ["Camarões (Cameroun)"]: "33",
  ["Canadá"]: "34",
  ["Chade"]: "35",
  ["Chile"]: "36",
  ["China, República Popular da"]: "37",
  ["Chipre"]: "38",
  ["Colômbia"]: "39",
  ["Comores (Comoros)"]: "40",
  ["República do Congo"]: "41",
  ["Costa Rica"]: "43",
  ["Costa do Marfim"]: "42",
  ["Croácia"]: "44",
  ["Cuba"]: "45",
  ["Dinamarca"]: "46",
  ["Djibuti"]: "47",
  ["Dominica"]: "48",
  ["Equador"]: "49",
  ["Egito"]: "50",
  ["El Salvador"]: "51",
  ["Emirados Árabes Unidos"]: "52",
  ["Eritréia"]: "53",
  ["Eslováquia"]: "54",
  ["Eslovênia"]: "55",
  ["Espanha"]: "56",
  ["Bolívia"]: "23",
  ["Micronésia"]: "116",
  ["Estados Unidos"]: "57",
  ["Estônia"]: "58",
  ["Etiópia"]: "59",
  ["Macedônia"]: "60",
  ["Federação da Rússia"]: "61",
  ["Fiji"]: "62",
  ["Filipinas"]: "63",
  ["Finlândia"]: "64",
  ["França"]: "65",
  ["Gabão"]: "66",
  ["Gâmbia"]: "67",
  ["Geórgia"]: "68",
  ["Gana"]: "69",
  ["Gibraltar"]: "230",
  ["Granada"]: "70",
  ["Grécia"]: "71",
  ["Groenlândia"]: "203",
  ["Guadalupe"]: "210",
  ["Guam"]: "204",
  ["Guatemala"]: "72",
  ["Guiana Francesa"]: "208",
  ["Guernsey"]: "231",
  ["Guiné"]: "73",
  ["Guiné-Bissau"]: "74",
  ["Guiné Equatorial"]: "75",
  ["Guiana"]: "76",
  ["Haiti"]: "77",
  ["Honduras"]: "78",
  ["Hungria"]: "79",
  ["Índia"]: "80",
  ["Indonésia"]: "81",
  ["Iraque"]: "83",
  ["Irlanda"]: "84",
  ["Islândia"]: "85",
  ["Ilhas Alanda"]: "207",
  ["Ilhas Caymans"]: "228",
  ["Ilhas Cocos"]: "200",
  ["Ilhas Cook"]: "219",
  ["Ilhas Feroé"]: "202",
  ["Ilhas Malvinas"]: "229",
  ["Ilhas Marianas"]: "205",
  ["Ilhas Marshall"]: "86",
  ["Ilha de Christmas (Ilha do Natal)"]: "199",
  ["Ilha Norfolk"]: "201",
  ["Ilha Reunião"]: "214",
  ["Ilhas Salomão"]: "87",
  ["Ilhas Turks e Caicos"]: "240",
  ["Ilhas Virgens Britânicas"]: "241",
  ["Ilhas Virgens dos Estados Unidos"]: "206",
  ["Ilhas Wallis e Futuna"]: "217",
  ["Israel"]: "88",
  ["Itália"]: "89",
  ["Jamaica"]: "91",
  ["Japão"]: "92",
  ["Jordânia"]: "93",
  ["Cazaquistão"]: "94",
  ["Quênia"]: "95",
  ["Quirguistão"]: "96",
  ["Kiribati"]: "97",
  ["(Kuwait)"]: "98",
  ["Lesoto"]: "99",
  ["Letônia"]: "100",
  ["Líbano"]: "101",
  ["Libéria"]: "102",
  ["Líbia"]: "90",
  ["Liechtenstein"]: "103",
  ["Lituânia"]: "104",
  ["Luxemburgo"]: "105",
  ["Madagascar"]: "106",
  ["Malásia"]: "107",
  ["Maláui"]: "108",
  ["Maldivas"]: "109",
  ["Mali"]: "110",
  ["Malta"]: "111",
  ["Marrocos"]: "112",
  ["Martinica"]: "211",
  ["Maurício"]: "113",
  ["Mauritânia"]: "114",
  ["Mayotte"]: "212",
  ["Mônaco"]: "117",
  ["Mongólia"]: "118",
  ["Montenegro"]: "119",
  ["Montserrat"]: "233",
  ["Moçambique"]: "120",
  ["União de Myanmar"]: "121",
  ["Namíbia"]: "122",
  ["Nauru"]: "123",
  ["Nicarágua"]: "124",
  ["Níger"]: "125",
  ["Nigéria"]: "126",
  ["Niue"]: "220",
  ["Noruega"]: "127",
  ["Nova Caledônia"]: "213",
  ["Nova Zelândia"]: "128",
  ["Omã"]: "129",
  ["Países Baixos (Holanda)"]: "130",
  ["Paquistão"]: "131",
  ["Palau"]: "132",
  ["Palestina"]: "133",
  ["Panamá"]: "134",
  ["Papua Nova Guiné"]: "135",
  ["Paraguai"]: "136",
  ["Perú"]: "137",
  ["Ilhas Pitcairn"]: "234",
  ["Polinésia Francesa"]: "209",
  ["Polônia"]: "138",
  ["Portugal"]: "139",
  ["Porto Rico"]: "140",
  ["Catar (Qatar)"]: "142",
  ["Macau"]: "195",
  ["Hong Kong"]: "194",
  ["Reino Unido"]: "143",
  ["Síria"]: "144",
  ["Saara Ocidental (República Árabe Saaráui Democrática)"]: "198",
  ["Venezuela"]: "189",
  ["República Centro-Africana"]: "145",
  ["República Tcheca"]: "146",
  ["Coréia do Sul"]: "147",
  ["Moldávia"]: "148",
  ["República Democrática do Congo"]: "149",
  ["Laos"]: "150",
  ["República Dominicana"]: "151",
  ["Nepal"]: "152",
  ["Irã"]: "82",
  ["Coréia do Norte"]: "153",
  ["Tanzânia"]: "154",
  ["Romênia"]: "155",
  ["Ruanda"]: "156",
  ["São Cristóvão e Névis"]: "235",
  ["Samoa (Samoa Ocidental)"]: "157",
  ["San Bartolomeu"]: "215",
  ["São Marino"]: "158",
  ["Ilha de São Martinho"]: "224",
  ["São Pedro e Miquelão"]: "216",
  ["São Vicente e Granadinas"]: "237",
  ["Santa Helena"]: "238",
  ["Santa Lúcia"]: "236",
  ["Vaticano"]: "197",
  ["São Tomé e Príncipe"]: "159",
  ["Senegal"]: "160",
  ["Sérvia"]: "161",
  ["Sérvia e Montenegro"]: "243",
  ["Seychelles"]: "162",
  ["Serra Leoa"]: "163",
  ["Cingapura (Singapura)"]: "164",
  ["Somália"]: "165",
  ["Sri Lanka"]: "166",
  ["África do Sul"]: "167",
  ["Sudão"]: "168",
  ["Sudán del Sur"]: "262",
  ["Suécia"]: "169",
  ["Suíça"]: "170",
  ["Suriname"]: "171",
  ["Svalbard e Jan Mayen"]: "218",
  ["Suazilândia"]: "172",
  ["Tailândia"]: "173",
  ["Taiwan"]: "174",
  ["Tajiquistão"]: "175",
  ["Território Britânico do Oceano Índico"]: "227",
  ["Timor Leste"]: "176",
  ["Togo"]: "177",
  ["Toquelau"]: "221",
  ["Tonga"]: "178",
  ["Trindade e Tobago"]: "179",
  ["Tunísia"]: "180",
  ["Turcomenistão (Turquemenistão)"]: "181",
  ["Turquia"]: "182",
  ["Tuvalu"]: "183",
  ["Ucrânia"]: "184",
  ["Uganda"]: "185",
  ["Uruguai"]: "186",
  ["Uzbequistão"]: "187",
  ["Vanuatu"]: "188",
  ["Vietnã"]: "190",
  ["Iêmen"]: "191",
  ["Zâmbia"]: "192",
  ["Zimbábue"]: "193",
};

const paisExpedicionPasaporteIds = {
  ["Brasil"]: "26",
  ["Federação da Rússia"]: "61",
  ["Turquia"]: "182",
  ["Ucrânia"]: "184",
};

const motivoIds = {
  ["Turismo"]: "904",
  ["Negócios"]: "906",
  ["Di¿er"]: "2962",
};

const residenciaIds = {
  ["Afeganistão"]: "1",
  ["Albânia"]: "2",
  ["Alemanha"]: "3",
  ["Andorra"]: "4",
  ["Angola"]: "5",
  ["Anguilla"]: "225",
  ["Antígua e Barbuda"]: "6",
  ["Antilhas Neerlandesas (Antilhas Holandesas)"]: "223",
  ["Arábia Saudita"]: "7",
  ["Argélia"]: "8",
  ["Argentina"]: "9",
  ["Armênia"]: "10",
  ["Aruba"]: "222",
  ["Austrália"]: "11",
  ["Áustria"]: "12",
  ["Azerbaijão"]: "13",
  ["Bahamas"]: "14",
  ["Bareine (Bahrein)"]: "15",
  ["Bangladeche (Bangladesh)"]: "16",
  ["Barbados"]: "17",
  ["Bielorrússia (Belarus)"]: "18",
  ["Bélgica"]: "19",
  ["Belize"]: "20",
  ["Benin"]: "21",
  ["Bermudas"]: "226",
  ["Butão"]: "22",
  ["Bósnia e Herzegovina"]: "24",
  ["Botsuana"]: "25",
  ["Brasil"]: "26",
  ["Brunei Darussalam"]: "27",
  ["Bulgária"]: "28",
  ["Burkina Faso"]: "29",
  ["Burundi"]: "30",
  ["Cabo Verde"]: "31",
  ["Camboja"]: "32",
  ["Camarões (Cameroun)"]: "33",
  ["Canadá"]: "34",
  ["Chade"]: "35",
  ["Chile"]: "36",
  ["China, República Popular da"]: "37",
  ["Chipre"]: "38",
  ["Colômbia"]: "39",
  ["Comores (Comoros)"]: "40",
  ["República do Congo"]: "41",
  ["Costa Rica"]: "43",
  ["Costa do Marfim"]: "42",
  ["Croácia"]: "44",
  ["Cuba"]: "45",
  ["Dinamarca"]: "46",
  ["Djibuti"]: "47",
  ["Dominica"]: "48",
  ["Equador"]: "49",
  ["Egito"]: "50",
  ["El Salvador"]: "51",
  ["Emirados Árabes Unidos"]: "52",
  ["Eritréia"]: "53",
  ["Eslováquia"]: "54",
  ["Eslovênia"]: "55",
  ["Espanha"]: "56",
  ["Bolívia"]: "23",
  ["Micronésia"]: "116",
  ["Estados Unidos"]: "57",
  ["Estônia"]: "58",
  ["Etiópia"]: "59",
  ["Macedônia"]: "60",
  ["Federação da Rússia"]: "61",
  ["Fiji"]: "62",
  ["Filipinas"]: "63",
  ["Finlândia"]: "64",
  ["França"]: "65",
  ["Gabão"]: "66",
  ["Gâmbia"]: "67",
  ["Geórgia"]: "68",
  ["Gana"]: "69",
  ["Gibraltar"]: "230",
  ["Granada"]: "70",
  ["Grécia"]: "71",
  ["Groenlândia"]: "203",
  ["Guadalupe"]: "210",
  ["Guam"]: "204",
  ["Guatemala"]: "72",
  ["Guiana Francesa"]: "208",
  ["Guernsey"]: "231",
  ["Guiné"]: "73",
  ["Guiné-Bissau"]: "74",
  ["Guiné Equatorial"]: "75",
  ["Guiana"]: "76",
  ["Haiti"]: "77",
  ["Honduras"]: "78",
  ["Hungria"]: "79",
  ["Índia"]: "80",
  ["Indonésia"]: "81",
  ["Iraque"]: "83",
  ["Irlanda"]: "84",
  ["Islândia"]: "85",
  ["Ilhas Alanda"]: "207",
  ["Ilhas Caymans"]: "228",
  ["Ilhas Cocos"]: "200",
  ["Ilhas Cook"]: "219",
  ["Ilhas Feroé"]: "202",
  ["Ilhas Malvinas"]: "229",
  ["Ilhas Marianas"]: "205",
  ["Ilhas Marshall"]: "86",
  ["Ilha de Christmas (Ilha do Natal)"]: "199",
  ["Ilha Norfolk"]: "201",
  ["Ilha Reunião"]: "214",
  ["Ilhas Salomão"]: "87",
  ["Ilhas Turks e Caicos"]: "240",
  ["Ilhas Virgens Britânicas"]: "241",
  ["Ilhas Virgens dos Estados Unidos"]: "206",
  ["Ilhas Wallis e Futuna"]: "217",
  ["Israel"]: "88",
  ["Itália"]: "89",
  ["Jamaica"]: "91",
  ["Japão"]: "92",
  ["Jordânia"]: "93",
  ["Cazaquistão"]: "94",
  ["Quênia"]: "95",
  ["Quirguistão"]: "96",
  ["Kiribati"]: "97",
  ["(Kuwait)"]: "98",
  ["Lesoto"]: "99",
  ["Letônia"]: "100",
  ["Líbano"]: "101",
  ["Libéria"]: "102",
  ["Líbia"]: "90",
  ["Liechtenstein"]: "103",
  ["Lituânia"]: "104",
  ["Luxemburgo"]: "105",
  ["Madagascar"]: "106",
  ["Malásia"]: "107",
  ["Maláui"]: "108",
  ["Maldivas"]: "109",
  ["Mali"]: "110",
  ["Malta"]: "111",
  ["Marrocos"]: "112",
  ["Martinica"]: "211",
  ["Maurício"]: "113",
  ["Mauritânia"]: "114",
  ["Mayotte"]: "212",
  ["Mônaco"]: "117",
  ["Mongólia"]: "118",
  ["Montenegro"]: "119",
  ["Montserrat"]: "233",
  ["Moçambique"]: "120",
  ["União de Myanmar"]: "121",
  ["Namíbia"]: "122",
  ["Nauru"]: "123",
  ["Nicarágua"]: "124",
  ["Níger"]: "125",
  ["Nigéria"]: "126",
  ["Niue"]: "220",
  ["Noruega"]: "127",
  ["Nova Caledônia"]: "213",
  ["Nova Zelândia"]: "128",
  ["Omã"]: "129",
  ["Países Baixos (Holanda)"]: "130",
  ["Paquistão"]: "131",
  ["Palau"]: "132",
  ["Palestina"]: "133",
  ["Panamá"]: "134",
  ["Papua Nova Guiné"]: "135",
  ["Paraguai"]: "136",
  ["Perú"]: "137",
  ["Ilhas Pitcairn"]: "234",
  ["Polinésia Francesa"]: "209",
  ["Polônia"]: "138",
  ["Portugal"]: "139",
  ["Porto Rico"]: "140",
  ["Catar (Qatar)"]: "142",
  ["Macau"]: "195",
  ["Hong Kong"]: "194",
  ["Reino Unido"]: "143",
  ["Síria"]: "144",
  ["Saara Ocidental (República Árabe Saaráui Democrática)"]: "198",
  ["Venezuela"]: "189",
  ["República Centro-Africana"]: "145",
  ["República Tcheca"]: "146",
  ["Coréia do Sul"]: "147",
  ["Moldávia"]: "148",
  ["República Democrática do Congo"]: "149",
  ["Laos"]: "150",
  ["República Dominicana"]: "151",
  ["Nepal"]: "152",
  ["Irã"]: "82",
  ["Coréia do Norte"]: "153",
  ["Tanzânia"]: "154",
  ["Romênia"]: "155",
  ["Ruanda"]: "156",
  ["São Cristóvão e Névis"]: "235",
  ["Samoa (Samoa Ocidental)"]: "157",
  ["San Bartolomeu"]: "215",
  ["São Marino"]: "158",
  ["Ilha de São Martinho"]: "224",
  ["São Pedro e Miquelão"]: "216",
  ["São Vicente e Granadinas"]: "237",
  ["Santa Helena"]: "238",
  ["Santa Lúcia"]: "236",
  ["Vaticano"]: "197",
  ["São Tomé e Príncipe"]: "159",
  ["Senegal"]: "160",
  ["Sérvia"]: "161",
  ["Sérvia e Montenegro"]: "243",
  ["Seychelles"]: "162",
  ["Serra Leoa"]: "163",
  ["Cingapura (Singapura)"]: "164",
  ["Somália"]: "165",
  ["Sri Lanka"]: "166",
  ["África do Sul"]: "167",
  ["Sudão"]: "168",
  ["Sudán del Sur"]: "262",
  ["Suécia"]: "169",
  ["Suíça"]: "170",
  ["Suriname"]: "171",
  ["Svalbard e Jan Mayen"]: "218",
  ["Suazilândia"]: "172",
  ["Tailândia"]: "173",
  ["Taiwan"]: "174",
  ["Tajiquistão"]: "175",
  ["Território Britânico do Oceano Índico"]: "227",
  ["Timor Leste"]: "176",
  ["Togo"]: "177",
  ["Toquelau"]: "221",
  ["Tonga"]: "178",
  ["Trindade e Tobago"]: "179",
  ["Tunísia"]: "180",
  ["Turcomenistão (Turquemenistão)"]: "181",
  ["Turquia"]: "182",
  ["Tuvalu"]: "183",
  ["Ucrânia"]: "184",
  ["Uganda"]: "185",
  ["Uruguai"]: "186",
  ["Uzbequistão"]: "187",
  ["Vanuatu"]: "188",
  ["Vietnã"]: "190",
  ["Iêmen"]: "191",
  ["Zâmbia"]: "192",
  ["Zimbábue"]: "193",
};

const visitoMexicoIds = {
  ["Sim"]: "true",
  ["Não"]: "false",
};

const religionIds = {
  ["Católica apostólica romana"]: "167",
  ["Ortodoxa"]: "168",
  ["Protestante"]: "169",
  ["Outra religião cristã"]: "170",
  ["Judaica"]: "171",
  ["Budista"]: "172",
  ["Hindú"]: "173",
  ["Islâmica"]: "174",
  ["Outra religião"]: "175",
  ["Nenhuma religião (ateu)"]: "176",
};

const actividadIds = {
  ["Trabalha"]: "112",
  ["Estuda"]: "113",
  ["Casa"]: "114",
  ["Aposentado ou pensionista"]: "115",
  ["Ministro de religião"]: "116",
  ["Desempregado"]: "117",
  ["Menor dependiente económico"]: "2347",
};

const expulsadoIds = {
  ["Sim"]: "true",
  ["Não"]: "false",
};

const antecedentesIds = {
  ["Sim"]: "true",
  ["Não"]: "false",
};

module.exports = {
  sexoIds,
  nacionalidadIds,
  estadoCivilIds,
  paisNacimientoIds,
  paisExpedicionPasaporteIds,
  motivoIds,
  residenciaIds,
  visitoMexicoIds,
  religionIds,
  actividadIds,
  expulsadoIds,
  antecedentesIds,
};
